name: Deploy to Firebase Hosting (live)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # (optional) also set it job-wide so any npm CLI calls see it too
    env:
      FIREBASE_CLI_EXPERIMENTS: webframeworks

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install deps
        run: npm ci

      - name: Deploy (Frameworks)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_DAYORA_APP }}
          projectId: dayora-app
          channelId: live
          entryPoint: .
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks # 👈 required
